"""add lat and lon fields to query_responses table

Revision ID: 0314db0be7fd
Revises: 01a8a969ae44
Create Date: 2025-07-08 20:00:48.743180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0314db0be7fd'
down_revision: Union[str, Sequence[str], None] = '01a8a969ae44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_responses', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('query_responses', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_responses', 'lon')
    op.drop_column('query_responses', 'lat')
    # ### end Alembic commands ###
