"""create query_excludes table

Revision ID: 1347194d374a
Revises: f939d7444edd
Create Date: 2025-07-08 19:22:50.296983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1347194d374a'
down_revision: Union[str, Sequence[str], None] = 'f939d7444edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_excludes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('queries', 'exclude')
    op.drop_column('queries', 'response_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('response_json', sqlite.JSON(), nullable=True))
    op.add_column('queries', sa.Column('exclude', sqlite.JSON(), nullable=True))
    op.drop_table('query_excludes')
    # ### end Alembic commands ###
