"""add indexes

Revision ID: 87aee1726ff1
Revises: 0314db0be7fd
Create Date: 2025-07-08 22:30:35.713027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87aee1726ff1'
down_revision: Union[str, Sequence[str], None] = '0314db0be7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_query_city_text', 'queries', ['city', 'text'], unique=False)
    op.create_index(op.f('ix_query_excludes_query_id'), 'query_excludes', ['query_id'], unique=False)
    op.create_index('ix_queryresponse_query_id_name', 'query_responses', ['query_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_queryresponse_query_id_name', table_name='query_responses')
    op.drop_index(op.f('ix_query_excludes_query_id'), table_name='query_excludes')
    op.drop_index('ix_query_city_text', table_name='queries')
    # ### end Alembic commands ###
