"""add field city to query table

Revision ID: f939d7444edd
Revises: 759ef9ce022d
Create Date: 2025-07-07 21:19:57.283734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f939d7444edd'
down_revision: Union[str, Sequence[str], None] = '759ef9ce022d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'city')
    # ### end Alembic commands ###
